---
application:
  name: "glitch-typescript-baseplate"
  project: "bobbime"
  organization: "QoveryCommunity"
routers:
- name: "main-glitch-typescript-baseplate"
  routes:
  - application_name: "glitch-typescript-baseplate"
    paths:
    - "/*"
